- name: @dailydotdev/devcard
  # You may pin to the exact commit or the version.
  # uses: dailydotdev/action-devcard@07bed7718f1db1fbe2d96fe676a5f031d343ce4c
  uses: dailydotdev/action-devcard@2.1.0
  with:
    # The ID of the devcard
    devcard_id: 2b14cfca423648ea9ee8a0ddb84990f5
    # GitHub Token used to commit the devcard
    token: # optional, default is ${{ github.token }}
    # Branch used to commit the devcard
    commit_branch: # optional, default is 
    # Commit message
    commit_message: # optional, default is Update ${filename}
    # Filename to save devcard to
    commit_filename: # optional, default is devcard.svg
    # If true, no changes will be made to the repo
    dryrun: # optional
